package com.ExceptionEx;

public class Exception3
{
	public static void nain(String args[])
	{
		try
		{	
				int a[]=new int[5];
				a[10]=50;
		}
		
				catch(Exception e)
				
				{
		System.out.println("Exception caught");
				}
	}				
}